### ISSUE TITLE
Automate Accounts 

### ISSUE THREAD

**Issue by ghost** [MerryFairyTalesAD440/Operations#11]

**Comment by cjshaw** [comment]
Estimated time 2 hours.

**Comment by cjshaw** [comment]
[store-auto-ad440-2349.zip](https://github.com/MerryFairyTalesAD440/Builds/files/2801266/store-auto-ad440-2349.zip)

Actual time about 4 hours all told.

Question:
Do we need to hide the variable like Subscription ID and Deployment Name?
Do we want more than just a powershell script?  IE a bash script or something instead or in addition?

**Comment by cjshaw** [comment]
adding automation for all resource groups and resources.
est. 2 hours

**Comment by cjshaw** [comment]
Combined scripts and updated my task information on the wiki: https://github.com/MerryFairyTalesAD440/Builds/tree/clint_sp2_branch/DevOpsroot/Automation_Scripts

**Comment by cjshaw** [comment]
1. Link to branch: https://github.com/MerryFairyTalesAD440/Builds/tree/clint_sp2_branch/DevOpsroot/Automation_Scripts
2. Link to wiki:  https://github.com/MerryFairyTalesAD440/Builds/wiki/ARM-Automation-scripts-for-both-UI-and-API
3. Link to pull request: https://github.com/MerryFairyTalesAD440/Builds/pull/21
4. Time Estimate: 2 hours
   Actual Time: 18 hours

**Comment by toddysm** [comment]
Closing this. We will need to do some improvements of the scripts but will create new tasks for that.
