### ISSUE TITLE
Create Travis CI pipeline for ui dev and ui prod storage resources

### ISSUE THREAD

**Issue by cjshaw** [MerryFairyTalesAD440/Operations#16]
There are two storage accounts, one that holds all the static web content and one that will be the upload/download file server for the books.

The web storage resources are the ones labeled with web.

We need to create a Travis ci pipeline that uploads all folders and files related to the website on both develop and production.  These need to be separate so you must specify when to deploy to what.

use this github for reference: 
https://github.com/cjshaw/cloud-prac-storage-2349

the script needs to be altered to upload everything not just one file.

**Comment by DnlBell** [comment]
Added a upload.js file to the vueStarter branch.  It is being ran on travis when it is called. Currently cannot upload "dist" files resulting from the build process. Error is   "The specifed resource name contains invalid characters." Need to discuss with peers what to do next. 

Current time spent 3 hours

**Comment by DnlBell** [comment]
Using the storage account ui template and the azure storage vs code tools I have hosted the vue starter files as a static site from a blob. 

Current time spent 4.5 hours

**Comment by DnlBell** [comment]
Upload.js is now creating an identical folder structure in azure but when you go to the url the site only downloads the index file

current time spent 8.5 hours

**Comment by DnlBell** [comment]
This task is ready for review. Wiki page is here:

https://github.com/MerryFairyTalesAD440/Builds/wiki/UI-deployment-pipline-to-Azure-Via-Travis-CI

**Comment by DnlBell** [comment]
Added some conditional deployment to the travis.yml file

**Comment by DnlBell** [comment]
https://github.com/MerryFairyTalesAD440/UX-UI/pull/33
