### ISSUE TITLE
Key vault research

### ISSUE THREAD

**Issue by cjshaw** [MerryFairyTalesAD440/Operations#19]
Clint created a key vault resource.   Someone needs to figure out key vault and how it works.

**Comment by ryanybrennan** [comment]
https://github.com/MerryFairyTalesAD440/Builds/wiki/Research-Azure-Key-Vault

**Comment by ryanybrennan** [comment]
Estimated Time: ~3 hours
Actual Time: ~7 hours

**Comment by toddysm** [comment]
Closing this. We discussed the use of Key Vault. We will proceed with using it as discussed.
