### ISSUE TITLE
Automate name RG

### ISSUE THREAD

**Issue by D3v0nM** [MerryFairyTalesAD440/Operations#24]

**Comment by cjshaw** [comment]
EST. Time: 3 Hours
Actual Time: 6 hours

Changed resource naming.
Had issue running into duplicate names conflicting.
Wiki: [Link to wiki page](https://github.com/MerryFairyTalesAD440/Builds/wiki/Resource-Naming-conventions:-1box,-dev,-and-prod)

Pull request has been merged with development.

Bug: https://github.com/merryfairytalesad440/builds/issues/34
