### ISSUE TITLE
PROD API Travis CI Pipeline silently failing on deployment for travis-ci.com

### ISSUE THREAD

**Issue by ryanybrennan** [MerryFairyTalesAD440/Operations#44]
Task #38 

The production branch of the API pipeline to Travis CI is silently failing on travis-ci.com, but not travis-ci.org. It may be because of this that the production resource group is not properly being deployed to. The following links illustrate the issue:

https://travis-ci.org/MerryFairyTalesAD440/API/builds/501703573
This pipeline is deploying just fine. Details are in the job log by clicking on the Deploying Application job in the log.

https://travis-ci.com/MerryFairyTalesAD440/API/builds/104174560#L520
This pipeline appears to pass, but if you go to the job log and click on the Deploying Application job in the log, you will see details that provide evidence that the deployment is failing.

**Comment by cjshaw** [comment]
Azure functions need to be V2.  They have been switched back to v2
